<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.8"/>
    <xacro:property name="chassis_width" value="0.44"/>
    <xacro:property name="chassis_height" value="0.6"/>
    <xacro:property name="chassis_mass" value="30.0"/>
    <xacro:property name="rear_wheel_radius" value="0.1"/>
    <xacro:property name="rear_wheel_thickness" value="0.06"/>
    <xacro:property name="rear_wheel_mass" value="0.25"/>
    <xacro:property name="rear_wheel_offset_x" value="0.075"/>
    <xacro:property name="rear_wheel_offset_y" value="0.26"/>
    <xacro:property name="rear_wheel_offset_z" value="0.01"/>
    <xacro:property name="front_wheel_radius" value="0.1"/>
    <xacro:property name="front_wheel_thickness" value="0.06"/>
    <xacro:property name="front_wheel_mass" value="0.25"/>
    <xacro:property name="front_wheel_offset_x" value="-0.65"/>
    <xacro:property name="front_wheel_offset_y" value="-0.26"/>
    <xacro:property name="front_wheel_offset_z" value="0.01"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-rear_wheel_offset_x} 0 ${-rear_wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT REAR WHEEL LINK -->

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_rear_wheel"/>
        <origin xyz="0 ${rear_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${rear_wheel_mass}" length="${rear_wheel_thickness}" radius="${rear_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT REAR WHEEL LINK -->

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_rear_wheel"/>
        <origin xyz="0 ${-rear_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${rear_wheel_radius}" length="${rear_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${rear_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${rear_wheel_mass}" length="${rear_wheel_thickness}" radius="${rear_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


 
    <!-- LEFT FRONT WHEEL LINK -->

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="${-front_wheel_offset_x} ${-front_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${front_wheel_mass}" length="${front_wheel_thickness}" radius="${front_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT FRONT WHEEL LINK -->

    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="${-front_wheel_offset_x} ${front_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${front_wheel_mass}" length="${front_wheel_thickness}" radius="${front_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- SURTUNME KATSAYILARI -->

    <gazebo reference="left_front_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="left_rear_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="right_front_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="right_rear_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

</robot>